# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-Qt"
BBFILE_PATTERN_meta-Qt = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-Qt = "6"

LAYERDEPENDS_meta-Qt = "core"
LAYERSERIES_COMPAT_meta-Qt = "kirkstone"
