# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-bkk-display"
BBFILE_PATTERN_meta-bkk-display = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-bkk-display = "6"

LAYERDEPENDS_meta-bkk-display = "core openembedded-layer"
LAYERSERIES_COMPAT_meta-bkk-display = "kirkstone"
