# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /data/projects/yocto/poky/meta \
  /data/projects/yocto/poky/meta-poky \
  /data/projects/yocto/poky/meta-yocto-bsp \
  /data/projects/yocto/meta-raspberrypi \
  /data/projects/bkk_display/meta-platform-config \
  "
