# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /data/projects/yocto/poky/meta \
  /data/projects/yocto/poky/meta-poky \
  /data/projects/yocto/poky/meta-yocto-bsp \
  /data/projects/yocto/meta-raspberrypi \
  /data/projects/yocto/meta-openembedded/meta-oe \
  /data/projects/bkk_display/meta-platform-config \
  /data/projects/bkk_display/meta-display-config \
  /data/projects/bkk_display/meta-BKK-api \
  /data/projects/bkk_display/meta-bkk-setup \
  /data/projects/bkk_display/meta-Qt \
  /data/projects/yocto/meta-qt5 \
  /data/projects/bkk_display/build-rpi/workspace \
  "
